arussim:
  ros__parameters:
    imu:
      imu_frequency: 240.0         # Hz  Publish rate
      noise_imu_yaw: 0.01          # rad Noise standard deviation
      noise_imu_vx: 0.01          # m/s Noise standard deviation
      noise_imu_vy: 0.01          # m/s Noise standard deviation
      noise_imu_r: 0.01          # rad/s Noise standard deviation
    
    wheel_speed:
      wheel_speed_frequency: 1000.0    # Hz  Publish rate
      noise_wheel_speed_front_right: 0.01     # m/s Noise standard deviation (front right wheel)
      noise_wheel_speed_front_left: 0.01     # m/s Noise standard deviation (front left wheel)
      noise_wheel_speed_rear_right: 0.01     # m/s Noise standard deviation (rear right wheel)
      noise_wheel_speed_rear_left: 0.01     # m/s Noise standard deviation (rear left wheel)

    extensometer:
      extensometer_frequency: 100.0     # Hz  Publish rate
      noise_extensometer: 0.01     # m   Noise standard deviation
