name: docs_pages_workflow

on:
  push:
    branches:
      - main

jobs:

  build_docs_job:
    runs-on: ubuntu-22.04
    container: debian:buster-slim

    steps:

    - name: Checkout
      uses: actions/checkout@v3
    - name: Execute script to build our documentation and update pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ".github/scripts/buildDocs.sh"
      shell: bash
