name: Compile and Lint Check

on:
  push:
    branches:
      - 'feature/**'

  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup ROS2 Humble
        run: |
          sudo apt update
          sudo apt install ros-humble-desktop
          source /opt/ros/humble/setup.bash

      - name: Install dependencies
        run: |
          sudo apt install python3-colcon-common-extensions
          rosdep init
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Compile the code
        run: |
          # Compilar todos los paquetes dentro de la carpeta "src"
          colcon build --packages-up-to --event-handlers console_cohesion+

      - name: Run tests
        run: |
          # Ejecutar todas las pruebas en todos los paquetes
          colcon test --event-handlers console_cohesion+

      - name: Linter Check (cpp and python)
        run: |
          sudo apt install ros-humble-ament-cmake
          # Ejecuta el linter en todos los paquetes
          ament_lint_auto --all

      - name: C++ Style Check
        run: |
          # Ejecutar clang-format para C++
          clang-format -i --style=Google $(find ./src -name '*.cpp' -or -name '*.hpp')
          ament_cpplint .

      - name: Set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8

        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82,E101,E112 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-complexity=10 --statistics
          
      - name: Test with pytest
        run: |
          pytest
